function getSetupGuideText() {
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const siteUrl = (process.env.SITE_URL || 'https://dj-xpress.com').replace(/\/+$/, '');

  return `DJXPRESS — SETUP & MAINTENANCE GUIDE
Generated: ${generatedAt}
This file can be re-downloaded anytime from /admin/setup-guide on the site.

This document explains, in order, everything that had to be built, bought,
or signed up for to get ${siteUrl} up and running — so if anything ever
needs to be recreated, changed, or handed off to someone else, this is the
map of every piece and how they connect.

=====================================================================
WHAT THIS WEBSITE IS
=====================================================================
A booking + live song-request site for DJXpress:
  - A home page and a booking form for new clients
  - The QR code (shown on the admin dashboard) points to the homepage
    (${siteUrl}/), so guests can choose Book Now or Live Requests
  - A live page (${siteUrl}/live) where guests request songs, watch a
    live "Up Next" / "Recently Played" board, chat back and forth with
    the DJ in real time (no name needed; inappropriate language is
    blocked before it's sent), see a live "how many people are here"
    counter, tap floating emoji reactions, vote on the DJ's quick polls,
    and leave a note in the guestbook
  - Every one of those four extras (guest counter, reactions, polls,
    guestbook) can be switched on/off any time from the dashboard,
    without losing anything already saved

EVERY TOOL AND ACCOUNT THIS SITE TOUCHES, AT A GLANCE
  Claude Code (claude.ai/code)  The AI coding assistant used to write,
                                 debug, deploy, and maintain this entire
                                 site through conversation — this guide
                                 was generated by it. Any AI coding tool
                                 (Claude Code, Cursor, etc.) can open the
                                 GitHub repo in section 1 and keep working
                                 on it the same way; nothing here locks
                                 the code to one specific tool.
  GitHub                        Where the code itself lives — section 1
  Cloudflare                    Domain name + DNS — section 2
  Render                        Hosting — where the site actually runs — section 3
  Resend                        Email notifications — section 4
  AudD                          Automatic song detection (audio recognition) — section 5
  Twilio                        Text message notifications — coming soon, section 6
  - An admin dashboard (${siteUrl}/admin) for running the event: going
    live, marking/accepting requests, automatic song detection, replying
    in the live chat, viewing past events' full setlists and chat logs,
    and managing booking inquiries

=====================================================================
1. THE WEBSITE'S CODE
=====================================================================
- Lives on GitHub: https://github.com/toneztvv/DjBooking-
- Branch running in production: claude/djxpress-booking-live-requests-a569sk
- Built with Node.js + Express + SQLite — no build step, runs anywhere
  Node runs
- The full README.md in that repo has setup instructions too, kept in
  sync with this guide

=====================================================================
2. THE DOMAIN NAME — dj-xpress.com
=====================================================================
- Registered at: Cloudflare — dash.cloudflare.com
- Cost: roughly $10–12/year, renews automatically unless cancelled there
- DNS records configured (Cloudflare → the domain → DNS → Records):

    Type: A       Name: @      Value: 216.24.57.1              Proxy: DNS only (grey cloud)
    Type: CNAME   Name: www    Value: djxpress.onrender.com     Proxy: DNS only (grey cloud)

  IMPORTANT: both records must stay set to "DNS only" (grey cloud icon),
  never "Proxied" (orange cloud) — Cloudflare's proxy breaks how Render
  serves the site and shows a Cloudflare error page instead of the
  actual website. If the site ever shows a Cloudflare-branded error
  page, this is the first thing to check.

=====================================================================
3. HOSTING — RENDER (dashboard.render.com)
=====================================================================
- This is where the actual website runs, 24/7.
- Service name: djxpress
- Plan: a paid 0.5 CPU / 512MB instance (~$7/month) plus a 1GB persistent
  disk (~$0.25/month) mounted at /opt/render/project/src/data
- Why paid, specifically: Render's free tier resets all data (bookings,
  song requests, event history) every time the service restarts or goes
  idle, and blocks some outbound network connections. The disk is what
  makes data permanent.
- Deploys automatically: connected directly to the GitHub repo above.
  Every time new code is pushed to the branch listed in section 1, Render
  rebuilds and redeploys within a couple of minutes on its own — nothing
  to click.
- There's also a render.yaml file in the repo that defines this
  configuration as code. Render can auto-sync a service to match that
  file on every deploy — if the file and the dashboard ever disagree,
  Render's own dashboard will warn about it, and the file should be
  updated to match reality (this has already happened once — render.yaml
  originally said "free" plan before the account was upgraded, and got
  corrected to match).

ENVIRONMENT VARIABLES (Render → djxpress → Environment tab)
These are the settings and secrets the site needs to run. To see or
change an actual current value, open that Environment tab and click the
eye icon next to it (this guide intentionally does not include the
actual secret values, since it's a plain text file — treat the Render
dashboard itself as the source of truth for those).

  PORT                  Which network port the app listens on (Render sets this automatically)
  SITE_URL              The real website address: ${siteUrl}/
  ADMIN_USER            Username for logging into /admin
  ADMIN_PASSWORD        Password for logging into /admin
  GMAIL_USER            Which email address receives booking notifications (see section 4)
  RESEND_API_KEY        Lets the site send those email notifications (see section 4)
  AUDD_API_KEY          Powers automatic song detection (see section 5)
  TWILIO_ACCOUNT_SID    Text message notifications — NOT YET SET UP, see section 6
  TWILIO_AUTH_TOKEN     (same — coming soon)
  TWILIO_FROM_NUMBER    (same — coming soon)
  NOTIFY_PHONE_NUMBER   (same — coming soon)

=====================================================================
4. EMAIL NOTIFICATIONS — RESEND (resend.com)
=====================================================================
Purpose: sends an email to whatever address GMAIL_USER is set to, every
time someone submits a booking inquiry on the website.
Cost: free, up to 3,000 emails/month. No card required.
How it was set up:
  1. Created a free account at resend.com
  2. Went to resend.com/api-keys → "Create API Key" → copied it
  3. Pasted that key into Render's Environment tab as RESEND_API_KEY
  4. Set GMAIL_USER to the email address that should receive them
     (despite the name, it doesn't have to be a Gmail address)
To check usage or manage the account: log into resend.com

Why Resend instead of just sending straight through Gmail: most hosts,
Render included, block or time out direct SMTP connections (the
protocol email clients like Gmail use) as spam prevention. Resend sends
over a normal HTTPS API call instead, which isn't subject to that.

=====================================================================
5. AUTOMATIC SONG DETECTION — AUDD (audd.io)
=====================================================================
Purpose: lets the DJ hit "Start Listening" on the admin dashboard while
live. It samples the room's audio through whatever device's microphone
is running the page, every 30–90 seconds, and identifies the song via
AudD's recognition API — automatically marking a matching request as
played, or logging it under "DJ Pick" in the setlist if nobody
requested it.
Cost: first 300 recognitions free (no card needed to start), then about
$5 per 1,000 recognitions.
How it was set up:
  1. Created a free account at audd.io
  2. Copied the API key from the account page
  3. Pasted it into Render's Environment tab as AUDD_API_KEY
Important limitation (not fixable in code — it's how iOS/Android work):
this only works while the browser tab is open and visible. Locking the
phone or switching apps suspends microphone access. Works best left
running on the DJ laptop, or a phone dedicated to nothing else during
the set.
To check usage or manage the account: log into audd.io

=====================================================================
6. TEXT MESSAGE NOTIFICATIONS — TWILIO (COMING SOON — NOT YET ACTIVE)
=====================================================================
Purpose, once turned on: texts a phone number the moment someone submits
a booking, or requests a song that nobody's already asked for this event
(no repeat text for a song that gets requested by several more guests).
Cost: NOT free — roughly $1/month for the phone number, plus about 1
cent per text sent. Twilio requires adding a card to the account, unlike
Resend and AudD.
Status: the website's code already fully supports this. It was built
and tested, then intentionally left turned off because adding a card
wasn't wanted at the time. Email notifications and the live dashboard
already cover the same need in the meantime.
To turn it on whenever ready:
  1. Create an account at twilio.com and add a payment method
  2. From the Twilio Console (console.twilio.com), copy the Account SID
     and Auth Token shown on the main dashboard
  3. Buy a phone number to send from: Console → Phone Numbers → Buy a
     number (~$1/month)
  4. In Render's Environment tab, add all four:
       TWILIO_ACCOUNT_SID   = (from step 2)
       TWILIO_AUTH_TOKEN    = (from step 2)
       TWILIO_FROM_NUMBER   = (the number from step 3, as +1XXXXXXXXXX)
       NOTIFY_PHONE_NUMBER  = (the real cell number to text, as +1XXXXXXXXXX)
  5. Save. Texting starts working immediately — no code changes needed.

=====================================================================
7. THE ADMIN PANEL — WHAT EACH PAGE DOES
=====================================================================
Log in at: ${siteUrl}/admin
  (username and password = the ADMIN_USER / ADMIN_PASSWORD values from
  section 3 — check Render's Environment tab if they're ever forgotten)

  Dashboard              /admin              Go live / end event, clear
                                              the board, accept and mark
                                              requests played, Auto Song
                                              Detection, reply in the
                                              live chat, post/close a
                                              quick poll, turn the guest
                                              counter/reactions/polls/
                                              guestbook on or off, the
                                              QR code, a summary of new
                                              inquiries
  Guestbook              /admin/guestbook    Every guestbook note across
                                              every event, with a delete
                                              button per entry
  Event History          /admin/events       Every past event, each with
                                              its full setlist in the
                                              order songs were played,
                                              its full chat log, every
                                              poll's final results, and
                                              that event's guestbook notes
  Booking Inquiries      /admin/inquiries    Everyone who's submitted the
                                              booking form, contact info,
                                              and a status you can update
  Services & Billing     /admin/services     One-click links to every
                                              paid account this site
                                              depends on
  This Guide             /admin/setup-guide  This document, downloadable
                                              any time

=====================================================================
8. IF SOMETHING BREAKS — QUICK TROUBLESHOOTING NOTES
=====================================================================
- Site shows a 502 error: almost always just mid-restart or mid-deploy
  on Render. Wait a minute or two and refresh.
- Site shows a Cloudflare-branded error page ("DNS points to prohibited
  IP" or similar): a DNS record at dash.cloudflare.com got switched to
  "Proxied" (orange cloud) instead of "DNS only" (grey cloud). Edit the
  record and switch it back — see section 2.
- Bookings or song requests disappearing after a while: check that
  Render's disk is still attached (djxpress → Disk tab) and the plan is
  still the paid one, not Free (djxpress → Settings). If render.yaml in
  the GitHub repo ever gets pushed with different values than what's
  actually configured, Render's auto-sync can revert the live settings
  to match the file — always double check the plan and disk after any
  code update if data ever goes missing.
- Emails, song detection, or (once turned on) texts stop working: check
  that service's own dashboard (resend.com / audd.io / twilio.com) for
  account or billing issues, and confirm the matching environment
  variable in Render's Environment tab is still set correctly.

=====================================================================
END OF GUIDE
=====================================================================
`;
}

module.exports = { getSetupGuideText };
